from datetime import datetime
import os


def generate_report(target_url, crawl_results, findings, total_score=None, output_dir="reports"):
    """
    Generates a Markdown report summarizing the scan: target info,
    crawl statistics, and all findings grouped by risk level, sorted
    by severity score within each group. Returns the report file path.
    """
    os.makedirs(output_dir, exist_ok=True)

    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    filename = f"scan_report_{timestamp}.md"
    filepath = os.path.join(output_dir, filename)

    risk_order = ["High", "Medium", "Low", "Info"]
    grouped = {level: [] for level in risk_order}
    for finding in findings:
        risk = finding.get("risk", "Info")
        grouped.setdefault(risk, []).append(finding)

    if total_score is None:
        total_score = sum(f.get("score", 0) for f in findings)

    lines = []
    lines.append("# FortifyWebX Scan Report")
    lines.append("")
    lines.append(f"**Target:** {target_url}")
    lines.append(f"**Scan Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"**Overall Risk Score:** {total_score}")
    lines.append("")
    lines.append("## Crawl Summary")
    lines.append("")
    lines.append(f"- Pages discovered: {len(crawl_results['pages'])}")
    lines.append(f"- Forms discovered: {len(crawl_results['forms'])}")
    lines.append(f"- Hidden fields discovered: {len(crawl_results['hidden_fields'])}")
    lines.append(f"- Inline scripts discovered: {len(crawl_results['inline_scripts'])}")
    lines.append("")
    lines.append("## Findings Summary")
    lines.append("")
    lines.append("| Risk Level | Count | Score Each |")
    lines.append("|---|---|---|")
    score_map = {"High": 9, "Medium": 6, "Low": 3, "Info": 1}
    for level in risk_order:
        lines.append(f"| {level} | {len(grouped[level])} | {score_map[level]} |")
    lines.append(f"| **Total Findings** | **{len(findings)}** | **Risk Score: {total_score}** |")
    lines.append("")

    for level in risk_order:
        level_findings = sorted(grouped[level], key=lambda f: f.get("score", 0), reverse=True)
        if not level_findings:
            continue
        lines.append(f"## {level} Risk Findings ({len(level_findings)})")
        lines.append("")
        for i, finding in enumerate(level_findings, 1):
            lines.append(f"### {i}. {finding['name']} (Score: {finding.get('score', '-')})")
            lines.append("")
            lines.append(f"- **Location:** {finding['location']}")
            lines.append(f"- **Evidence:** {finding['evidence']}")
            lines.append(f"- **Description:** {finding['description']}")
            lines.append("")

    lines.append("---")
    lines.append("*Report generated by FortifyWebX Scanner - non-intrusive scan only, no exploitation attempted.*")

    with open(filepath, "w") as f:
        f.write("\n".join(lines))

    return filepath


# Maps common Unicode punctuation (that Helvetica's Latin-1-only core
# font can't render) to safe ASCII equivalents. PDF export uses this;
# the Markdown report above is untouched since Markdown/text files
# handle Unicode fine.
UNICODE_TO_ASCII = {
    "\u2014": "-",   # em dash
    "\u2013": "-",   # en dash
    "\u2018": "'",   # left single quote
    "\u2019": "'",   # right single quote
    "\u201c": '"',   # left double quote
    "\u201d": '"',   # right double quote
    "\u2026": "...", # ellipsis
    "\u2022": "-",   # bullet
}


def _sanitize_for_pdf(text):
    """
    Replaces Unicode punctuation with ASCII equivalents, then strips
    any remaining character outside Latin-1 as a final safety net.
    Prevents FPDFUnicodeEncodingException, which is raised when text
    contains a character outside the Helvetica core font's supported
    range (Latin-1 only, not full Unicode).
    """
    if text is None:
        return ""
    text = str(text)
    for uni_char, ascii_char in UNICODE_TO_ASCII.items():
        text = text.replace(uni_char, ascii_char)
    text = text.encode("latin-1", errors="ignore").decode("latin-1")
    return text


def _safe_wrap(pdf, text, max_width_ratio=0.85):
    """
    Breaks any 'word' (unbroken run of non-space characters) that is
    wider than the printable page width, using FPDF's own font metrics
    (pdf.get_string_width) rather than guessing a character count.
    Also sanitizes Unicode characters first via _sanitize_for_pdf.

    This prevents two classic FPDF failure modes:
      1. FPDFException: "Not enough horizontal space to render a
         single character" (caused by long unbroken strings like URLs)
      2. FPDFUnicodeEncodingException (caused by Unicode punctuation
         not supported by the core Helvetica font)
    """
    text = _sanitize_for_pdf(text)
    usable_width = (pdf.w - pdf.l_margin - pdf.r_margin) * max_width_ratio

    words = text.split(" ")
    result_words = []

    for word in words:
        if pdf.get_string_width(word) <= usable_width:
            result_words.append(word)
            continue

        chunk = ""
        for ch in word:
            test_chunk = chunk + ch
            if pdf.get_string_width(test_chunk) > usable_width:
                result_words.append(chunk)
                chunk = ch
            else:
                chunk = test_chunk
        if chunk:
            result_words.append(chunk)

    return " ".join(result_words)


def generate_pdf_report(target_url, crawl_results, findings, total_score=None, output_dir="reports"):
    """
    Generates a PDF version of the scan report using fpdf2. Mirrors
    the structure of the Markdown report but as a standalone PDF
    deliverable, suitable for sharing with non-technical stakeholders.
    """
    from fpdf import FPDF

    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    filename = f"scan_report_{timestamp}.pdf"
    filepath = os.path.join(output_dir, filename)

    if total_score is None:
        total_score = sum(f.get("score", 0) for f in findings)

    risk_order = ["High", "Medium", "Low", "Info"]
    grouped = {level: [] for level in risk_order}
    for finding in findings:
        risk = finding.get("risk", "Info")
        grouped.setdefault(risk, []).append(finding)

    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 12, "FortifyWebX Scan Report", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 11)
    pdf.multi_cell(0, 8, _safe_wrap(pdf, f"Target: {target_url}"))
    pdf.cell(0, 8, f"Scan Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 8, f"Overall Risk Score: {total_score}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 10, "Crawl Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 7, f"Pages discovered: {len(crawl_results['pages'])}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 7, f"Forms discovered: {len(crawl_results['forms'])}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 7, f"Hidden fields discovered: {len(crawl_results['hidden_fields'])}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 7, f"Inline scripts discovered: {len(crawl_results['inline_scripts'])}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 10, "Findings Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 11)
    for level in risk_order:
        pdf.cell(0, 7, f"{level}: {len(grouped[level])} finding(s)", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    for level in risk_order:
        level_findings = sorted(grouped[level], key=lambda f: f.get("score", 0), reverse=True)
        if not level_findings:
            continue

        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 10, f"{level} Risk Findings ({len(level_findings)})", new_x="LMARGIN", new_y="NEXT")

        for i, finding in enumerate(level_findings, 1):
            pdf.set_x(pdf.l_margin)
            pdf.set_font("Helvetica", "B", 11)
            pdf.multi_cell(0, 7, _safe_wrap(pdf, f"{i}. {finding['name']} (Score: {finding.get('score', '-')})"))

            pdf.set_x(pdf.l_margin)
            pdf.set_font("Helvetica", "", 10)
            pdf.multi_cell(0, 6, _safe_wrap(pdf, f"Location: {finding['location']}"))

            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(0, 6, _safe_wrap(pdf, f"Evidence: {finding['evidence']}"))

            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(0, 6, _safe_wrap(pdf, f"Description: {finding['description']}"))
            pdf.ln(3)

    pdf.set_font("Helvetica", "I", 9)
    pdf.set_x(pdf.l_margin)
    pdf.multi_cell(0, 6, _safe_wrap(pdf, "Report generated by FortifyWebX Scanner -- non-intrusive scan only, no exploitation attempted."))

    pdf.output(filepath)
    return filepath
